AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - config/unicorn.rb
    - db/**
  NewCops: enable

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['^(\s*#)']
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
    - data_services_api.gemspec

Style/Documentation:
  Exclude:
    - test/**/*

Style/OptionalBooleanParameter:
  Enabled: false
