module DataServicesApi
  # A sub-type of RuntimeError for problems that arise when interacting with the
  # DS API
  class ServiceException < RuntimeError
    @status: untyped

    @source: untyped

    @service_message: untyped

    attr_reader status: untyped

    attr_reader source: untyped

    attr_reader service_message: untyped

    def initialize: (untyped msg, untyped status, ?untyped? source, ?untyped? service_message) -> void
  end
end
