name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Publish to GitHub Package Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Build gem
        run: gem build data_services_api.gemspec

      - name: Publish to GitHub Package Registry
        run: gem push --key github --host https://rubygems.pkg.github.com/epimorphics *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
