name: typecheck.yml
on:
  pull_request:
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Install RBS collections
        run: rbs collection install

      - name: Run type checker
        run: bundle exec steep check --severity-level=error
