name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install dependencies (bundle)
      run: bundle install

    - name: Run tests
      run: rake test
      env:
        API_URL: http://localhost:8888
